config/routes.rb
Rails.application.routes.draw do
  get "/pages/*id" => "pages#show", format: false

  resources :entries do
    resources :notes, only: %i(create update)
  end

  namespace :api do
    resources :goals, only: %i(update)
  end

  root to: "pages#show", id: "home"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/entry.rb
class Entry < ApplicationRecord
  validates :date,
    uniqueness: { scope: :user_id, message: "already has an entry" }
  validates :date, presence: true

  has_many :goals, -> { order(id: :asc) }, dependent: :destroy
  has_one :note, dependent: :destroy
  belongs_to :user

  def goal_descriptions
    goals.map(&:description)
  end
end

app/models/entry_form.rb
class EntryForm
  include ActiveModel::Model

  attr_reader :entry, :goals, :note

  delegate :id, :persisted?, :date, to: :entry

  validate :validate_children

  def initialize(entry: nil)
    @new_record = true unless entry
    @entry = entry || Entry.new(date: Date.today)
    @note = @entry.note || @entry.build_note(content: "")
    @goals = if entry && entry_has_goals?
               entry.goals
             else
               Array.new(3) { Goal.new }
             end
  end

  def new_record?
    @new_record
  end

  def self.model_name
    Entry.model_name
  end

  def update_attributes(params)
    set_attributes(params)
    save
  end

  private

  def entry_has_goals?
    entry.goals.exists?
  end

  def set_attributes(date: nil, user: nil, goal_descriptions: [])
    entry.date = date
    entry.user = user
    goals.zip(goal_descriptions).each do |(goal, description)|
      goal.entry = entry
      goal.description = description
    end
  end

  def save
    if valid?
      ActiveRecord::Base.transaction do
        entry.save!
        goals.each(&:save!)
        note.save!
      end
    end
  end

  def validate_children
    if entry.invalid?
      promote_errors(entry.errors)
    end

    goals.each do |goal|
      if goal.invalid?
        promote_errors(goal.errors)
      end
    end

    if note.invalid?
      promote_errors(note.errors)
    end
  end

  def promote_errors(child_errors)
    child_errors.each do |attribute, message|
      errors.add(attribute, message)
    end
  end
end

app/models/goal.rb
class Goal < ApplicationRecord
  validates :description, length:
    { minimum: 0, allow_nil: false, message: "can't be nil" }
  validates_length_of :description, maximum: 255
  validates :completed, inclusion: { in: [true, false] }

  belongs_to :entry

  def self.with_descriptions
    where.not(description: "")
  end
end

app/models/note.rb
class Note < ApplicationRecord
  validates :content,
    length: { minimum: 0, allow_nil: false, message: "can't be nil" }
  validates :entry_id, uniqueness: true

  belongs_to :entry
end

app/models/tidbit.rb
class Tidbit
  attr_reader :title, :url

  def initialize(tidbit_data = {})
    @url = tidbit_data[:url]
    @title = tidbit_data[:title]
  end
end

app/models/tidbit_generator.rb
class TidbitGenerator
  def initialize(date)
    @date = date
    @source = StackOverflowApiIntegration.new(date)
    @tidbit = nil
  end

  def self.generate(date = Time.zone.today)
    new(date).tidbit
  end

  def tidbit
    @tidbit ||= Tidbit.new(@source.query)
  end
end

app/models/user.rb
class User < ApplicationRecord
  include Clearance::User

  has_many :entries

  def last_weeks_entries
    @last_weeks_entries ||= entries.
      where("date > ?", 1.week.ago).
      includes(:goals).
      includes(:note)
  end
end

app/controllers/api/goals_controller.rb
module Api
  class GoalsController < ApplicationController
    before_action :require_entry_to_belong_to_user

    def update
      goal.toggle(:completed)
      goal.save
    end

    private

    def goal
      @_goal ||= Goal.find(params[:id])
    end

    def entry
      @_entry_for_goal ||= goal.entry
    end

    def require_entry_to_belong_to_user
      unless entry.user == current_user
        head(403)
      end
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Clearance::Controller
  protect_from_forgery with: :exception
end

app/controllers/entries_controller.rb
class EntriesController < ApplicationController
  def new
    @entry_form = EntryForm.new
  end

  def create
    @entry_form = EntryForm.new

    if @entry_form.update_attributes(entry_form_params)
      flash[:success] = "Entry has been created"
      redirect_to entry_path(@entry_form.entry)
    else
      flash.now[:error] = @entry_form.errors.full_messages
      render :new
    end
  end

  def show
    @entry = Entry.find(params[:id])
    @goals = @entry.goals.with_descriptions
    @note = @entry.note
  end

  def index
    @entries = Entry.all
    @tidbit = TidbitGenerator.generate
  end

  def edit
    entry = Entry.includes(:goals).find(params[:id])
    @entry_form = EntryForm.new(entry: entry)
  end

  def update
    entry = Entry.includes(:goals).find(params[:id])
    @entry_form = EntryForm.new(entry: entry)

    if @entry_form.update_attributes(entry_form_params)
      flash[:success] = "Entry has been updated"
      redirect_to entry_path(@entry_form.entry)
    else
      flash.now[:error] = @entry_form.errors.full_messages
      render :edit
    end
  end

  def destroy
    entry = current_user.entries.find_by(id: params[:id])
    if entry.present?
      entry.destroy
      flash[:success] = "Entry has been deleted"
    else
      flash[:error] = "You are not authorized to delete this entry"
    end
    redirect_to entries_path
  end

  private

  def entry_form_params
    params.
      require(:entry_form).
      permit(:date, goal_descriptions: []).
      merge(user: current_user).
      to_h.
      symbolize_keys
  end
end

app/controllers/notes_controller.rb
class NotesController < ApplicationController
  before_action :require_entry_to_belong_to_user

  def create
    @entry = entry
    note = Note.new(content: note_params[:content], entry: @entry)
    persist_note_and_redirect(note: note, entry: @entry, params: note_params)
  end

  def update
    @entry = entry
    note = @entry.note
    persist_note_and_redirect(note: note, entry: @entry, params: note_params)
  end

  private

  def note_params
    params.require(:note).permit(:content)
  end

  def require_entry_to_belong_to_user
    unless entry.user == current_user
      flash[:error] = "Entry does not belong to you"
      redirect_to entries_path
    end
  end

  def persist_note_and_redirect(note:, entry:, params:)
    if note.update_attributes(params)
      flash[:success] = "Note Saved"
    else
      flash[:error] = note.errors.full_messages
    end
    redirect_to entry_path(entry)
  end

  def entry
    @_entry_for_notes ||= Entry.find(params[:entry_id])
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  include HighVoltage::StaticPage
  before_action :require_login
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/flashes_helper.rb
module FlashesHelper
  def user_facing_flashes
    flash.to_hash.slice("alert", "error", "notice", "success")
  end
end

app/views/application/_analytics.html.erb
<% if ENV["SEGMENT_KEY"] %>
  <script type="text/javascript">
    !function(){var analytics=window.analytics=window.analytics||[];if(!analytics.initialize)if(analytics.invoked)window.console&&console.error&&console.error("Segment snippet included twice.");else{analytics.invoked=!0;analytics.methods=["trackSubmit","trackClick","trackLink","trackForm","pageview","identify","reset","group","track","ready","alias","debug","page","once","off","on"];analytics.factory=function(t){return function(){var e=Array.prototype.slice.call(arguments);e.unshift(t);analytics.push(e);return analytics}};for(var t=0;t<analytics.methods.length;t++){var e=analytics.methods[t];analytics[e]=analytics.factory(e)}analytics.load=function(t){var e=document.createElement("script");e.type="text/javascript";e.async=!0;e.src=("https:"===document.location.protocol?"https://":"http://")+"cdn.segment.com/analytics.js/v1/"+t+"/analytics.min.js";var n=document.getElementsByTagName("script")[0];n.parentNode.insertBefore(e,n)};analytics.SNIPPET_VERSION="4.0.0";
    analytics.load("<%= ENV["SEGMENT_KEY"] %>");
    analytics.page();
    }}();
  </script>
<% end %>

app/views/application/_css_overrides.html.erb
<% if Rails.env.test? %>
  <style type="text/css">
    * {
      transition-property: none !important;
    }
  </style>
<% end %>

app/views/application/_flashes.html.erb
<div class="flashes-container">
  <% if flash.any? %>
    <div class="flashes">
      <% user_facing_flashes.each do |key, value| %>
        <div class="flash-<%= key %>"><%= value %></div>
      <% end %>
    </div>
  <% end %>
</div>

app/views/application/_javascript.html.erb
<%= javascript_include_tag :application %>

<%= yield :javascript %>

<% if Rails.env.test? %>
  <%= javascript_tag do %>
    $.fx.off = true;
    $.ajaxSetup({ async: false });
  <% end %>
<% end %>

app/views/application/_navbar.html.erb
<div class="navbar" >
  <% if signed_in? %>
    <div class="entry-nav">
      <%= link_to "Entries Index", entries_path %>
      <%= link_to "New Entry", new_entry_path %>
    </div>

    <div class="user-nav">
      <%= current_user.email %>
      <%= link_to "Sign Out", sign_out_path, method: :delete %>
    </div>

  <% else %>
    <%= link_to "Sign In", sign_in_path %>
  <% end %>
</div>

app/views/entries/_entry_form.html.erb
<%= form_for @entry_form do |f| %>
  <input
    type="date"
    id="entry-date"
    name="entry_form[date]"
    value="<%= @entry_form.date %>"
   />
  <% @entry_form.goals.each_with_index do |goal, idx| %>
    <% goal_id = "goal-#{idx + 1}" %>
    <label for="<%= goal_id %>"><%= "Goal #{idx + 1}" %></label>
    <input
      type="text"
      name="entry_form[goal_descriptions][]"
      id="<%= goal_id %>"
      value="<%= goal.description %>"
    />
  <% end %>
  <%= submit_tag "#{@entry_form.new_record? ? 'Create' : 'Submit Edit'} Entry"  %>
<% end %>

app/views/entries/_note_form.html.erb
<%= form_for note, url: entry_note_path(entry, note) do |note_form| %>
  <%= note_form.text_area :content, class: "note-content" %>
  <%= note_form.submit "Save Notes" %>
<% end %>

app/views/entries/edit.html.erb
<h1 class="page-title">Edit Entry</h1>

<%= render 'entry_form' %>

app/views/entries/index.html.erb
<h1 class="page-title">Entries Index Page</h1>

<h2>Tidbit of the Day</h2>
<% if @tidbit %>
  <div class="tidbit-link">
    <%= link_to @tidbit.title, @tidbit.url %>
  </div>
<% end %>

<h2>Entries</h2>
<ul class="entries-list" />
  <% @entries.each do |entry| %>
    <li>
      <a
        href=<%= entry_path(entry) %>
        id=<%= "entry-id-#{entry.id}" %>
        class="entry-item"
      >
        <%= entry.date %>
      </a>
    </li>
  <% end %>
</ul>

app/views/entries/new.html.erb
<h1 class="page-title">Create a New Entry</h1>

<%= render 'entry_form' %>

app/views/entries/show.html.erb
<h1 class="page-title">Entry Show Page</h1>

<div class="entry-section">
  <h2>Date:</h2>
  <div class="goal-date"><%= @entry.date %></div>
</div>

<div class="entry-section">
  <h2>Goals:</h2>
  <ul class="goal-list">
  <% @goals.each do |goal| %>
    <% goal_id = "goal-#{goal.id}" %>
    <li class="goal-summary" >
      <label class="goal-checkbox-label">
        <%= check_box_tag goal_id, true, goal.completed,
          class: "goal-checkbox-input", data: { goal_id: goal.id }  %>
        <div class="goal-checkbox-content"><%= goal.description %></div>
      </label>
   </li>
  <% end %>
  </ul>
</div>

<div class="entry-section">
  <h2>Notes:</h2>
  <%= render "note_form", note: @note, entry: @entry %>
</div>

<% if @entry.user == current_user %>
  <div class="entry-section">
    <div class="mutation-buttons-container">
      <a class="button" href="<%= edit_entry_path(@entry)%>">Edit Entry</a>
      <%= button_to("Delete Entry", { action: "destroy", id: @entry.id },
                    method: "delete", 
                    data: { confirm: "Are you sure?",
                            disable_with: "loading..."}) %>
    </div>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8" />
  <meta name="ROBOTS" content="NOODP" />
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
  <title><%= title %></title>
  <%= stylesheet_link_tag :application, media: "all" %>
  <%= csrf_meta_tags %>
</head>
<body class="<%= body_class %>">
  <%= render "navbar" %>
  <%= render "flashes" %>
  <div class="page-content-container" >
    <%= yield %>
  </div>
  <%= render "javascript" %>
  <%= render "css_overrides" %>
</body>
</html>

app/views/pages/home.html.erb
<h1>Apprentice Journal Home Page</h1>